version: "3.9"

services:


  roll-call-backend:
    image: "callroll/backend"
    build: backend/
    env_file:
      - backend/.env
    container_name: "roll-call-backend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roll-backend.rule=Host(`demo.baff-business.com`) && PathPrefix(`/backend`)"
      - "traefik.http.routers.roll-backend.tls=true"
      - "traefik.http.routers.roll-backend.entrypoints=websecure"
      - "traefik.http.routers.roll-backend.tls.certresolver=myresolver"

    networks:
      proxy:
  roll-call-frontend:
    image: "callroll/frontend"
    build: frontend/
    container_name: "roll-call-frontend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roll-frontend.rule=Host(`demo.baff-business.com`) && ! PathPrefix(`/backend`)"
      - "traefik.http.routers.roll-frontend.tls=true"
      - "traefik.http.routers.roll-frontend.entrypoints=websecure"
      - "traefik.http.routers.roll-frontend.tls.certresolver=myresolver"
    networks:
      proxy:

networks:
  proxy:
    external: true