version: "3.9"

services:


  roll-call-backend:
    restart: always
    image: "callroll/backend"
    build: backend/
    env_file:
      - backend/.env
    volumes:
      - roll_call_media:/backend/media
      - roll_call_static:/backend/static
    container_name: "roll-call-backend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roll-backend.rule=Host(`demo.baff-business.com`) && PathPrefix(`/backend`)"
      - "traefik.http.routers.roll-backend.tls=true"
      - "traefik.http.routers.roll-backend.entrypoints=websecure"
      - "traefik.http.routers.roll-backend.tls.certresolver=myresolver"
    networks:
      proxy:
  roll-call-frontend:
    restart: always
    image: "callroll/frontend"
    build: frontend/
    volumes:
      - roll_call_media:/usr/share/nginx/html/media
      - roll_call_static:/usr/share/nginx/html/static
    container_name: "roll-call-frontend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roll-frontend.rule=Host(`demo.baff-business.com`) && ! PathPrefix(`/backend`)"
      - "traefik.http.routers.roll-frontend.tls=true"
      - "traefik.http.routers.roll-frontend.entrypoints=websecure"
      - "traefik.http.routers.roll-frontend.tls.certresolver=myresolver"
    networks:
      proxy:
  roll-call-db:
    image: postgres
    container_name: "roll-call-db"
    restart: always
    volumes:
      - roll_call_db_data:/var/lib/postgresql/data/
    env_file:
      - db.env
    networks:
      proxy:
networks:
  proxy:
    external: true
volumes:
  roll_call_db_data:
  roll_call_static:
  roll_call_media: